version: '3'

services:
  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ../public:/var/www
      - ./php-fpm/php.local.ini:/usr/local/etc/php/conf.d/php.local.ini
    environment:
      PHP_IDE_CONFIG: "serverName=docker-php-unit"
      PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/www/vendor/bin'
